

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: doctrine_association_mapping_php
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003

    ####################################################################################################
    # DATABASE (MySQL)
    # docker exec -it doctrine_association_mapping_mysql bash -c "mysql -u root -proot"
    ####################################################################################################
    doctrine_association_mapping_db:
        container_name: doctrine_association_mapping_mysql
        image: mysql:8.0
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: doctrine_association_mapping
            MYSQL_USER: doctrine_association_mapping_db_user
            MYSQL_PASSWORD: doctrine_association_mapping_db_pass

